apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: invoice-db
  labels:
    app: invoice-db
  namespace: villota
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice-db
  template:
    metadata:
      name: invoice-db
      labels:
        app: invoice-db
    spec:
      containers:
      - name: invoice-db
        image: underbedmonster/postgres:1.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
 name: invoice-db-service
 namespace: villota
 labels:
  app: invoice-db
spec:
 type: ClusterIP
 selector:
  app: invoice-db
 ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: http
